name: Build
on:
  push:
    branches:
      - "*"
    paths:
    - '**/*.go'
  pull_request:
    paths:
    - '**/*.go'
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Compile
        run: |
          make build
